<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Aborting_State" Id="{9ad29b47-7330-4ef2-b0c5-59754296754f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Aborting_State  IMPLEMENTS ITF_State
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	pPML_Base : POINTER TO PML_StatePattern_Base;
	_stateMachine : IPmlStateMachine;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Cycle" Id="{fec74ea0-3475-4a7b-9c64-7b4a1d2a7e0a}">
      <Declaration><![CDATA[METHOD Cycle : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_stateMachine.SetStateComplete();
pPML_Base^.SetState(pPML_Base^.aborted);
]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_init" Id="{e57274ba-de98-4eeb-b5e8-8765fcac59eb}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	pPML_Base : POINTER TO PML_StatePattern_Base;
	statemachine : IPmlStateMachine;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_stateMachine := statemachine;
THIS^.pPML_Base := pPML_Base;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="Aborting_State">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="Aborting_State.Cycle">
      <LineId Id="6" Count="1" />
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="Aborting_State.FB_init">
      <LineId Id="11" Count="0" />
      <LineId Id="10" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>