<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Clearing_State" Id="{1f23ff1c-63dc-4572-a7ac-ed0a233c0084}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Clearing_State  IMPLEMENTS ITF_State
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	pPML_Base : POINTER TO PML_StatePattern_Base;
	_stateMachine : IPmlStateMachine;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Cycle" Id="{67af2511-d343-491e-9dbd-7f9fb6470886}">
      <Declaration><![CDATA[METHOD Cycle : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_stateMachine.SetStateComplete();
pPML_Base^.SetState(pPML_Base^.stopped);
]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_init" Id="{7d0d3ea1-519d-47bd-aebe-ad8c7e3dea47}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	pPML_Base : POINTER TO PML_StatePattern_Base;
	statemachine : IPmlStateMachine;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_stateMachine := statemachine;
THIS^.pPML_Base := pPML_Base;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="Clearing_State">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="Clearing_State.Cycle">
      <LineId Id="6" Count="1" />
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="Clearing_State.FB_init">
      <LineId Id="11" Count="0" />
      <LineId Id="10" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>