<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="PML_Method_Base" Id="{e9cf9054-9269-474f-9eb2-f1589d2b309b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PML_Method_Base
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
VAR_IN_OUT
	ipackml : IPmlStateMachine;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[CASE ipackml.GetCurrentState() OF
	E_PMLState.ePMLState_Clearing:
		Clearing();
	E_PMLState.ePMLState_Aborted:
		Aborted();
	E_PMLState.ePMLState_Aborting:
		Aborting();
	E_PMLState.ePMLState_Complete:
		Completed();
	E_PMLState.ePMLState_Completing:
		Completing();
	E_PMLState.ePMLState_Execute:
		Execute();
	E_PMLState.ePMLState_Held:
		Held();
	E_PMLState.ePMLState_Holding:
		Holding();
	E_PMLState.ePMLState_Idle:
		Idle();
	E_PMLState.ePMLState_Resetting:
		Resetting();
	E_PMLState.ePMLState_Starting:
		Starting();
	E_PMLState.ePMLState_Stopped:
		Stopped();
	E_PMLState.ePMLState_Stopping:
		Stopping();
	E_PMLState.ePMLState_Suspended:
		Suspended();
	E_PMLState.ePMLState_Suspending:
		Suspending();
	E_PMLState.ePMLState_Undefined:
		Undefined();
	E_PMLState.ePMLState_Unholding:
		Unholding();
	E_PMLState.ePMLState_Unsuspending:
		Unsuspending();
END_CASE]]></ST>
    </Implementation>
    <Folder Name="Action_States" Id="{b5e75466-7e20-4308-9a0c-d79f927f78b2}" />
    <Folder Name="Wait_States" Id="{4ea05185-b1a4-4062-8470-b5d9cd15033c}" />
    <Method Name="Aborted" Id="{0b53e203-5e54-4083-a358-85f9fcb0b82d}" FolderPath="Wait_States\">
      <Declaration><![CDATA[METHOD PRIVATE Aborted : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Aborting" Id="{a238d54d-264d-44d5-8ffa-3c1950f83c82}" FolderPath="Action_States\">
      <Declaration><![CDATA[METHOD PRIVATE Aborting : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[ipackml.SetStateComplete();]]></ST>
      </Implementation>
    </Method>
    <Method Name="Clearing" Id="{bc0d4280-1f13-44f7-9829-54e43797220d}" FolderPath="Action_States\">
      <Declaration><![CDATA[METHOD PRIVATE Clearing : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[ipackml.SetStateComplete();]]></ST>
      </Implementation>
    </Method>
    <Method Name="Completed" Id="{a2cdb556-85a9-4482-9c68-efa360a9f3a8}" FolderPath="Wait_States\">
      <Declaration><![CDATA[METHOD PRIVATE Completed : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Completing" Id="{d000f392-3ce7-4095-9ef8-8fd0d9356f52}" FolderPath="Action_States\">
      <Declaration><![CDATA[METHOD PRIVATE Completing : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[ipackml.SetStateComplete();]]></ST>
      </Implementation>
    </Method>
    <Method Name="Execute" Id="{c7bd509a-3b83-4cba-a198-2c15be7394c6}" FolderPath="Wait_States\">
      <Declaration><![CDATA[METHOD PRIVATE Execute : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Held" Id="{43527c9b-adbe-4a8d-bea9-48bd143c16e1}" FolderPath="Wait_States\">
      <Declaration><![CDATA[METHOD PRIVATE Held : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Holding" Id="{51b21d7c-d045-491a-9230-89c46c7877ba}" FolderPath="Action_States\">
      <Declaration><![CDATA[METHOD PRIVATE Holding : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[ipackml.SetStateComplete();]]></ST>
      </Implementation>
    </Method>
    <Method Name="Idle" Id="{72ae97ce-bb49-416c-a0c3-2a5d5a89b363}" FolderPath="Wait_States\">
      <Declaration><![CDATA[METHOD PRIVATE Idle : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Resetting" Id="{a2baa753-5fca-484b-ac9d-210e1d858721}" FolderPath="Action_States\">
      <Declaration><![CDATA[METHOD PRIVATE Resetting : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[ipackml.SetStateComplete();]]></ST>
      </Implementation>
    </Method>
    <Method Name="Starting" Id="{7130edc4-9bcd-4f22-a7e3-a08ef79934ac}" FolderPath="Action_States\">
      <Declaration><![CDATA[METHOD PRIVATE Starting : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[ipackml.SetStateComplete();]]></ST>
      </Implementation>
    </Method>
    <Method Name="Stopped" Id="{9216c521-0aa8-4d36-b21b-e92e18d080de}" FolderPath="Wait_States\">
      <Declaration><![CDATA[METHOD PRIVATE Stopped : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Stopping" Id="{d1deb6dc-cf14-43e2-9c49-5843d0609c07}" FolderPath="Action_States\">
      <Declaration><![CDATA[METHOD PRIVATE Stopping : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[ipackml.SetStateComplete();]]></ST>
      </Implementation>
    </Method>
    <Method Name="Suspended" Id="{3a3bac37-3c3e-4d16-8e35-91a2f397e3f4}" FolderPath="Wait_States\">
      <Declaration><![CDATA[METHOD PRIVATE Suspended : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Suspending" Id="{2c5d472d-4db0-4bfa-8212-c6994a3a3a1e}" FolderPath="Action_States\">
      <Declaration><![CDATA[METHOD PRIVATE Suspending : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[ipackml.SetStateComplete();]]></ST>
      </Implementation>
    </Method>
    <Method Name="Undefined" Id="{c2968a58-cc56-487d-837d-e21cd9003270}" FolderPath="Wait_States\">
      <Declaration><![CDATA[METHOD PRIVATE Undefined : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Unholding" Id="{c38e73f1-8378-4b42-b35b-fb73989464ff}" FolderPath="Action_States\">
      <Declaration><![CDATA[METHOD PRIVATE Unholding : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[ipackml.SetStateComplete();]]></ST>
      </Implementation>
    </Method>
    <Method Name="Unsuspending" Id="{d39bdcd4-1b3a-4864-8589-79f8ff046f53}" FolderPath="Action_States\">
      <Declaration><![CDATA[METHOD PRIVATE Unsuspending : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[ipackml.SetStateComplete();]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="PML_Method_Base">
      <LineId Id="9" Count="0" />
      <LineId Id="12" Count="0" />
      <LineId Id="31" Count="0" />
      <LineId Id="14" Count="0" />
      <LineId Id="32" Count="0" />
      <LineId Id="15" Count="0" />
      <LineId Id="49" Count="0" />
      <LineId Id="16" Count="0" />
      <LineId Id="48" Count="0" />
      <LineId Id="17" Count="0" />
      <LineId Id="47" Count="0" />
      <LineId Id="18" Count="0" />
      <LineId Id="45" Count="0" />
      <LineId Id="19" Count="0" />
      <LineId Id="44" Count="0" />
      <LineId Id="20" Count="0" />
      <LineId Id="43" Count="0" />
      <LineId Id="21" Count="0" />
      <LineId Id="42" Count="0" />
      <LineId Id="22" Count="0" />
      <LineId Id="41" Count="0" />
      <LineId Id="23" Count="0" />
      <LineId Id="40" Count="0" />
      <LineId Id="24" Count="0" />
      <LineId Id="39" Count="0" />
      <LineId Id="25" Count="0" />
      <LineId Id="38" Count="0" />
      <LineId Id="26" Count="0" />
      <LineId Id="37" Count="0" />
      <LineId Id="27" Count="0" />
      <LineId Id="36" Count="0" />
      <LineId Id="28" Count="0" />
      <LineId Id="35" Count="0" />
      <LineId Id="29" Count="0" />
      <LineId Id="34" Count="0" />
      <LineId Id="30" Count="0" />
      <LineId Id="33" Count="0" />
      <LineId Id="13" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Base.Aborted">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Base.Aborting">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Base.Clearing">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Base.Completed">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Base.Completing">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Base.Execute">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Base.Held">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Base.Holding">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Base.Idle">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Base.Resetting">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Base.Starting">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Base.Stopped">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Base.Stopping">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Base.Suspended">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Base.Suspending">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Base.Undefined">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Base.Unholding">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Base.Unsuspending">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>