<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="PML_Method_Base" Id="{e9cf9054-9269-474f-9eb2-f1589d2b309b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PML_Method_Base
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Aborted" Id="{0b53e203-5e54-4083-a358-85f9fcb0b82d}">
      <Declaration><![CDATA[METHOD PRIVATE Aborted : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Aborting" Id="{a238d54d-264d-44d5-8ffa-3c1950f83c82}">
      <Declaration><![CDATA[METHOD PRIVATE Aborting : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Clearing" Id="{bc0d4280-1f13-44f7-9829-54e43797220d}">
      <Declaration><![CDATA[METHOD PRIVATE Clearing : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Completed" Id="{a2cdb556-85a9-4482-9c68-efa360a9f3a8}">
      <Declaration><![CDATA[METHOD PRIVATE Completed : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Completing" Id="{d000f392-3ce7-4095-9ef8-8fd0d9356f52}">
      <Declaration><![CDATA[METHOD PRIVATE Completing : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Execute_State" Id="{c7bd509a-3b83-4cba-a198-2c15be7394c6}">
      <Declaration><![CDATA[METHOD PRIVATE Execute_State : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Held" Id="{43527c9b-adbe-4a8d-bea9-48bd143c16e1}">
      <Declaration><![CDATA[METHOD PRIVATE Held : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Holding" Id="{51b21d7c-d045-491a-9230-89c46c7877ba}">
      <Declaration><![CDATA[METHOD PRIVATE Holding : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Idle" Id="{72ae97ce-bb49-416c-a0c3-2a5d5a89b363}">
      <Declaration><![CDATA[METHOD PRIVATE Idle : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Resetting" Id="{a2baa753-5fca-484b-ac9d-210e1d858721}">
      <Declaration><![CDATA[METHOD PRIVATE Resetting : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Starting" Id="{7130edc4-9bcd-4f22-a7e3-a08ef79934ac}">
      <Declaration><![CDATA[METHOD PRIVATE Starting : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Stopped" Id="{9216c521-0aa8-4d36-b21b-e92e18d080de}">
      <Declaration><![CDATA[METHOD PRIVATE Stopped : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Stopping" Id="{d1deb6dc-cf14-43e2-9c49-5843d0609c07}">
      <Declaration><![CDATA[METHOD PRIVATE Stopping : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Suspended" Id="{3a3bac37-3c3e-4d16-8e35-91a2f397e3f4}">
      <Declaration><![CDATA[METHOD PRIVATE Suspended : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Suspending" Id="{2c5d472d-4db0-4bfa-8212-c6994a3a3a1e}">
      <Declaration><![CDATA[METHOD PRIVATE Suspending : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Unholding" Id="{c38e73f1-8378-4b42-b35b-fb73989464ff}">
      <Declaration><![CDATA[METHOD PRIVATE Unholding : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Unsuspending" Id="{d39bdcd4-1b3a-4864-8589-79f8ff046f53}">
      <Declaration><![CDATA[METHOD PRIVATE Unsuspending : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="PML_Method_Base">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Base.Aborted">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Base.Aborting">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Base.Clearing">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Base.Completed">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Base.Completing">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Base.Execute_State">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Base.Held">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Base.Holding">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Base.Idle">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Base.Resetting">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Base.Starting">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Base.Stopped">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Base.Stopping">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Base.Suspended">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Base.Suspending">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Base.Unholding">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Base.Unsuspending">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>