<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN_1" Id="{8f22fbc4-6e57-419e-a6c2-cbf5c8ee4798}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN_1
VAR
	pmlbase : PML_Base;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN_1">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>