<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="Resetting_State" Id="{e487e0e3-f47e-443c-893c-c4527c851321}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Resetting_State  IMPLEMENTS ITF_State
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	pPML_Base : POINTER TO PML_Base;
	_stateMachine : IPmlStateMachine;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Cycle" Id="{33253227-e440-4391-8c6c-d0f15e86a992}">
      <Declaration><![CDATA[METHOD Cycle : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_stateMachine.SetStateComplete();
pPML_Base^.SetState(pPML_Base^.idle);
]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_init" Id="{4facd53f-ccf2-4cc0-b231-e70768116a76}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	pPML_Base : POINTER TO PML_Base;
	statemachine : IPmlStateMachine;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_stateMachine := statemachine;
THIS^.pPML_Base := pPML_Base;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="Resetting_State">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="Resetting_State.Cycle">
      <LineId Id="7" Count="1" />
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="Resetting_State.FB_init">
      <LineId Id="11" Count="0" />
      <LineId Id="10" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>