<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="PML_Method_Sample" Id="{7017d611-2e36-4a7a-a774-9234147f3ede}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PML_Method_Sample EXTENDS PML_Method_Base
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();]]></ST>
    </Implementation>
    <Method Name="Aborted" Id="{580d64fe-2185-4733-85c6-8a6e282a41d0}">
      <Declaration><![CDATA[METHOD PRIVATE Aborted : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Execute" Id="{8e750e4e-7ddf-4ca0-8a5d-59dbc11bd392}">
      <Declaration><![CDATA[METHOD PRIVATE Execute : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Idle" Id="{b462f406-7670-4d3a-b209-e255407c2bd1}">
      <Declaration><![CDATA[METHOD PRIVATE Idle : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Stopped" Id="{6f7d0af8-a71f-4c8d-a646-e440dc56bb6b}">
      <Declaration><![CDATA[METHOD PRIVATE Stopped : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="PML_Method_Sample">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Sample.Aborted">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Sample.Execute">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Sample.Idle">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="PML_Method_Sample.Stopped">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>