<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{42a06358-885d-4ebb-8314-bfbbbdbdf83c}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	pmlbase : PML_StatePattern_Base;
	packmlmachine : PMLStateMachine;
	pmlmethod : PML_Method_Sample := (PackMLStateMachine := packmlmachine);
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[packmlmachine();
pmlmethod.Cycle();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="13" Count="0" />
      <LineId Id="20" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>